export const PRELOADER_HARD_FAIL_OPEN_MS = 2200;
export const PRELOADER_REVEAL_BUDGET_MS = 1000;
export const PRELOADER_REVEAL_SAFETY_MS = 200;
export const PRELOADER_SOFT_REVEAL_MS =
    PRELOADER_HARD_FAIL_OPEN_MS - PRELOADER_REVEAL_BUDGET_MS - PRELOADER_REVEAL_SAFETY_MS;
